// USER AUTH
export const LOGIN_USER = "LOGIN_USER";
export const SET_USER_AUTH = "SET_USER_AUTH";
export const LOGOUT_USER = "LOGOUT_USER";

// ENTITY MANAGEMENT
export const FETCH_MODULES = "FETCH_MODULES";
export const FETCH_MODULE = "FETCH_MODULE";

//  MODULE TRACKS
export const FETCH_MODULE_TRACKS = "FETCH_MODULE_TRACKS";
export const FETCH_MODULE_TRACKS_ERROR = "FETCH_MODULE_TRACKS_ERROR";
export const CREATE_MODULE_TRACK = "CREATE_MODULE_TRACK";
export const CREATE_MODULE_TRACK_ERROR = "CREATE_MODULE_TRACK_ERROR";
export const FETCH_MODULE_TRACK = "FETCH_MODULE_TRACK";
export const FETCH_MODULE_TRACK_ERROR = "FETCH_MODULE_TRACK_ERROR";
export const EDIT_MODULE_TRACK = "EDIT_MODULE_TRACK";
export const DELETE_MODULE_TRACK = "DELETE_MODULE_TRACK";
export const CREATE_MODULE_TRACK_MAPPING = "CREATE_MODULE_TRACK_MAPPING";
export const CREATE_MODULE_TRACK_MAPPING_ERROR =
  "CREATE_MODULE_TRACK_MAPPING_ERROR";
export const CREATE_USER_TRACK_MAPPING = "CREATE_USER_TRACK_MAPPING";
export const CREATE_USER_TRACK_MAPPING_ERROR =
  "CREATE_USER_TRACK_MAPPING_ERROR";

// ORGANIZTION

export const FETCH_ORGANIZATIONS = "FETCH_ORGANIZATIONS";
export const FETCH_ORGANIZATION_BATCHES = "FETCH_ORGANIZATION_BATCHES";
export const FETCH_ORGANIZATION_TRACKS = "FETCH_ORGANIZATION_TRACKS";
export const FETCH_ORGANIZATION_MODULES = "FETCH_ORGANIZATION_MODULES";
export const FETCH_USERS = "FETCH_USERS";

// Questions

export const FETCH_QUESTIONS = "FETCH_QUESTIONS";
export const FETCH_QUESTION_DETAIL = "FETCH_QUESTION_DETAIL";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const CREATE_QUESTION = "CREATE_QUESTION";

// SIMULATIONS

export const FETCH_MODULE_SIMULATION = "FETCH_MODULE_SIMULATION";
export const CREATE_SIMULATION_ORG_MAPPING = "CREATE_SIMULATION_ORG_MAPPING";
export const FETCH_SIMULATION_LIST = "FETCH_SIMULATION_LIST";
export const FETCH_SIMULATION = "FETCH_SIMULATION";
export const FETCH_DEFAULT_SIMULATIONS = "FETCH_DEFAULT_SIMULATIONS";

// CLEAR

export const CLEAR_MODULES = "CLEAR_MODULES";
export const CLEAR_SIMULATIONS = "CLEAR_SIMULATIONS";

// DONDON

export const FETCH_DONDON_LIST = "FETCH_DONDON_LIST";
export const FETCH_DONDON_DETAILS = "FETCH_DONDON_DETAILS";

export const FETCH_MAGICPHRASE_LIST = "FETCH_MAGICPHRASE_LIST";
export const FETCH_MAGICPHRASE_DETAILS = "FETCH_MAGICPHRASE_DETAILS";

// REGION

export const FETCH_REGIONS = "FETCH_REGIONS";
export const FETCH_STATES = "FETCH_STATES";

// FETCH_CONTENT_COMPLEXITY_LEVEL

export const FETCH_CONTENT_COMPLEXITY_LEVEL = "FETCH_CONTENT_COMPLEXITY_LEVEL";

export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_PARAMETERS = "FETCH_PARAMETERS";
export const FETCH_TAGS = "FETCH_TAGS";

export const ADD_MTF = "ADD_MTF";
export const FETCH_MTF_LIST = "FETCH_MTF_LIST";
export const MTF_EDIT = "MTF_EDIT";
export const FETCH_MTF_DETAILS = "FETCH_MTF_DETAILS";

export const ADD_QUAD = "ADD_QUAD";
export const FETCH_QUAD_LIST = "FETCH_QUAD_LIST";
export const QUAD_EDIT = "QUAD_EDIT";
export const FETCH_QUAD_DETAILS = "FETCH_QUAD_DETAILS";
