// USER AUTH
export const LOGIN_USER = "LOGIN_USER";
export const SET_USER_AUTH = "SET_USER_AUTH";
export const LOGOUT_USER = "LOGOUT_USER";

// ENTITY MANAGEMENT
export const FETCH_MODULES = "FETCH_MODULES"
export const FETCH_MODULE = "FETCH_MODULE"

//  MODULE TRACKS
export const FETCH_MODULE_TRACKS = "FETCH_MODULE_TRACKS"
export const CREATE_MODULE_TRACK = "CREATE_MODULE_TRACK"
export const FETCH_MODULE_TRACK = "FETCH_MODULE_TRACK"
export const EDIT_MODULE_TRACK = "EDIT_MODULE_TRACK"
export const DELETE_MODULE_TRACK = "DELETE_MODULE_TRACK"
export const CREATE_MODULE_TRACK_MAPPING = "CREATE_MODULE_TRACK_MAPPING";
export const CREATE_USER_TRACK_MAPPING = "CREATE_USER_TRACK_MAPPING";


// ORGANIZTION

export const FETCH_ORGANIZATIONS = "FETCH_ORGANIZATIONS"
export const FETCH_ORGANIZATION_BATCHES = "FETCH_ORGANIZATION_BATCHES";
export const FETCH_ORGANIZATION_TRACKS = "FETCH_ORGANIZATION_TRACKS";
